### PR TITLE
New note/hint/warning/seealso/etc title styles

### PR DESCRIPTION
**Pull request by kaitlynhova**
*making the titles have bold backgrounds and look a little better.
*Glitter, since I'm trapped on a plane flight tonight and wanted to knock this idea out.
*new main side bar pre-clicked link font size

### CODE REVIEW

**Comment by mrpollo** [comment]
can you post a screenshot here with the changes on this pr pleaaase?

**Comment by kaitlynhova** [comment]
Sure!  

New notes
screen shot 2015-06-19 at 12 08 59 pm

new font weights on side bar

screen shot 2015-06-19 at 12 09 29 pm

**Comment by hamishwillee** [comment]
@kaitlynhova I like the new notes very much. Some oddities - see "code block" following this tip in http://python.dronekit.io/examples/simple_goto.html

image

**Comment by kaitlynhova** [comment]
@hamishwillee how would you like the cod blocks to look?

**Comment by hamishwillee** [comment]
@kaitlynhova separated (from the preceding tip) :-). THanks!

**Comment by kaitlynhova** [comment]
@hamishwillee sure! Here is the PR: https://github.com/3drobotics/sphinx_3dr_theme/pull/30
*once @mrpollo has had a chance to merge it into production you can check it out ~

**Comment by hamishwillee** [comment]
@kaitlynhova Thanks!

**Pull request merged**
