### PR TITLE
making the size of bullets smaller

### PR DESCRIPTION
**Pull request by kaitlynhova**

### CODE REVIEW

**Comment by tcr3dr** [comment]
lgtm

**Comment by hamishwillee** [comment]
@tcr3dr Does not seem to have gone live (bullets still seem to be 30px rather than 17px)?

**Comment by mrpollo** [comment]
@hamishwillee he can't push, only I have the power!

**Comment by hamishwillee** [comment]
We're all powerless compared to you ... .sob

**Pull request merged**
