### PR TITLE
Vagrant environment

### LINKED ISSUE #11: Add a vagrantfile to make it easy to get up and running with this theme
I can't test changes to this properly because I cant get the build to run (using Vagrant).

I tried vagrantfile below in root, but can't get it to install all dependencies. Have assigned to the expert - that's you @mrpollo ! 

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "ubuntu/trusty64"

    config.vm.provision "shell", inline: <<-SHELL
        apt-get -y update
        echo "[Sphinx 3DR Theme]: Installing build essentials"
        apt-get -y install build-essential
        echo "[Sphinx 3DR Theme]: Installing Python Devel"
        apt-get -y install python-dev
        echo "[Sphinx 3DR Theme]: Installing pip ..."
        apt-get -y install python-pip
        easy_install -U pip
        echo "[Sphinx 3DR Theme]: Installing Sphinx ... "
        pip install sphinx
        echo "[Sphinx 3DR Theme]: Installing NPM ... "
        apt-get -y install npm
        echo "[Sphinx 3DR Theme]: Installing Bundler ... "
        gem install bundler
        echo "[Sphinx 3DR Theme]: Installing Bower ... "
        npm install -g bower
        echo "[Sphinx 3DR Theme]: Installing Grunt-cli ... "
        npm install -g grunt-cli
        echo "[Sphinx 3DR Theme]: Installing NPM requirements  ... "        
        npm install
        echo "[Sphinx 3DR Theme]: Installing Bower requirements  ... "  
        bower install
        echo "[Sphinx 3DR Theme]: Building"
        grunt build
    SHELL
end

```

### PR DESCRIPTION
**Pull request by mrpollo**
fixes #11

### CODE REVIEW

**Comment by mrpollo** [comment]
To start up the server

```
vagrant up
```

To run the dev server

```
./runserver.sh
```

you can then open your browser on address `http://127.0.0.1:9001`

cc @hamishwillee

**Comment by hamishwillee** [comment]
@mrpollo awesome!

**Comment by hamishwillee** [comment]
@mrpollo Will this run on windows? Firstly I ran this and the vagrant script exited on a lot of errors:

```
==> default: ERR!
==> default:
==> default: npm
==> default:
==> default: ERR!
==> default:  Additional logging details can be found in:
==> default: npm
==> default:
==> default: ERR!
==> default:      /vagrant/npm-debug.log
==> default: npm
==> default:
==> default: ERR!
==> default:
==> default: not ok code 0
==> default: [Sphinx 3DR Theme]: Installing Bower requirements  ...
==> default: bower ESUDO         Cannot be run with sudo
==> default:
==> default: Additional error details:
==> default: Since bower is a user command, there is no need to execute it with superuser permissions.
==> default: If you're having permission errors when using bower without sudo, please spend a few minutes learning more about how your system should work
==> default:
==> default: http://www.joyent.com/blog/installing-node-and-npm
==> default: https://gist.github.com/isaacs/579814
==> default:
==> default: You can however run a command with sudo using --allow-root option
==> default: [Sphinx 3DR Theme]: Building
==> default: grunt-cli: The grunt command line interface. (v0.1.13)
==> default: Fatal error: Unable to find local grunt.
==> default: If you're seeing this message, either a Gruntfile wasn't found or grunt
==> default: hasn't been installed locally to your project. For more information about
==> default: installing and configuring grunt, please see the Getting Started guide:
==> default: http://gruntjs.com/getting-started
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

Secondly, the dev server is a .sh file - doesn't that mean linux? In any case, on windows I get the following:

```
C:\Users\hamis_000\Documents\vagranttesting\sphinx_3dr_theme>runserver.sh
Welcome to Git (version 1.9.4-preview20140611)
                                                                    [ Read 3 lines
^G Get Help              ^O WriteOut              ^R Read File             ^Y Prev
Run 'git help git' to display the help index.     ^W Where Is              ^V Next
Run 'git help <command>' to display help for specific commands.
bash: -c: line 0: syntax error near unexpected token `('
bash: -c: line 0: `C:/Program Files (x86)/Git/vagrant/tools/dev.sh'
Connection to 127.0.0.1 closed.

C:\Users\hamis_000\Documents\vagranttesting\sphinx_3dr_theme>runserver.sh
Welcome to Git (version 1.9.4-preview20140611)


Run 'git help git' to display the help index.
Run 'git help <command>' to display help for specific commands.
bash: -c: line 0: syntax error near unexpected token `('
bash: -c: line 0: `C:/Program Files (x86)/Git/vagrant/tools/dev.sh'
Connection to 127.0.0.1 closed.

C:\Users\hamis_000\Documents\vagranttesting\sphinx_3dr_theme>sh runserver.sh
bash: C:/MinGW/msys/1.0/vagrant/tools/dev.sh: No such file or directory
Connection to 127.0.0.1 closed.
```

**Comment by mrpollo** [comment]
Not sure what happened to your provisioning but you would help if you could provide the log located inside that vagrant image on `/vagrant/npm-debug.log` 

`runserver.sh` is meant to run under bash or shell, by the look of your output it seems like your git client on windows has a built in shell that is trying to execute this script causing those errors, if you want to run the server on windows you need to run `vagrant ssh -c "/vagrant/tools/dev.sh"` let me know if that works (you need to resolve your NPM problems first else the server won't start)

**Comment by hamishwillee** [comment]
THanks, I've emailed you the log.

**Comment by hamishwillee** [comment]
@mrpollo I still want it :-)

**Pull request merged**
